### ISSUE TITLE
Cannot run. Homebridge service terminated

### ISSUE THREAD

**Issue by Guoer-xz** [seikan/homebridge-mi-air-purifier#1]
Following the prompt installation, the following error occurs after configuring the config

——————————————————————————————————————————

/usr/local/lib/node_modules/homebridge-mi-air-purifier/index.js:114
			if(this.device.mode == item[1]){
			              ^

TypeError: Cannot read property 'mode' of undefined
    at MiAirPurifier.getRotationSpeed (/usr/local/lib/node_modules/homebridge-mi-air-purifier/index.js:114:18)
    at emitThree (events.js:116:13)
    at Characteristic.RotationSpeed.emit (events.js:197:7)
    at Characteristic.RotationSpeed.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:129:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:650:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:614:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:204:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
logout

**Comment by seikan** [comment]
May I know what generation of air purifier are you using? Also what is the firmware version?

**Comment by Guoer-xz** [comment]
The smaller second generation purifier, the latest firmware 1.2.4_59

**Comment by seikan** [comment]
Have you installed the required library of this plugin?

`npm -g install miio`

**Comment by Guoer-xz** [comment]
Thank you for your answer, but after I installed the miio library again with sudo, the error message has changed

——————————————————————————————————————————————
/usr/local/lib/node_modules/homebridge-mi-air-purifier/index.js:143
		if(this.device.aqi > 200)
		              ^

TypeError: Cannot read property 'aqi' of undefined
    at MiAirPurifier.getAirQuality (/usr/local/lib/node_modules/homebridge-mi-air-purifier/index.js:143:17)
    at emitThree (events.js:116:13)
    at Characteristic.AirQuality.emit (events.js:197:7)
    at Characteristic.AirQuality.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:129:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:650:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:614:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:204:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)

**Comment by seikan** [comment]
If seems like the plugin is not able to locate your air purifier. Is the homebridge server and air purifier within same network?

Also, try to remove the plugin and install again.

`sudo npm -g uninstall homebridge-mi-air-purifier
sudo npm -g install homebridge-mi-air-purifier`

**Comment by Guoer-xz** [comment]
I'm sorry, my problem is not in the plug-in stage, I found the reason but temporarily do not know how to solve, I miio running miio --discover will find the air purifier, including several devices Token???, and many other devices OK, thank you for your patience to answer, if you have a good way, please thank you for pointing the way.

————————————————————————————————

Device ID: 13479916
Model info: Unknown 
Address: 192.168.1.123 
Token: ???
Support: Unknown

**Comment by besteric** [comment]
I use this plugin in my Synology server with docker, It's works for me, but i found lots of warnning message when i check the docker logs

seem likes from miio :)

```bash 
All packages installed (13 packages installed from npm registry, used 2s, speed 44.78kB/s, json 14(20.65kB), ta
rball 59.32kB)                                                                                                 
[miio@0.12.0] link /usr/local/bin/miio@ -> /usr/local/lib/node_modules/miio/cli/index.js                       
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.                        
*** WARNING *** Please fix your application to use the native API of Avahi!                                    
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>                  
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported part
ially) in the Apple Bonjour compatibility layer of Avahi.                                                      
*** WARNING *** Please fix your application to use the native API of Avahi!                                    
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegist
er>                
```

**Comment by Guoer-xz** [comment]
Thank you very much for your patient response. I want to complicate it. Re air the purifier at the meter house. Again, miio can find it. It's a great plug-in
