### ISSUE TITLE
Unexpected token function, fail to loading plugin.

### ISSUE THREAD

**Issue by huangbinapple** [seikan/homebridge-mi-air-purifier#54]
my node version is v6.14.3

```
[6/28/2018, 2:49:56 AM] ====================
[6/28/2018, 2:49:56 AM] ERROR LOADING PLUGIN homebridge-mi-air-purifier:
[6/28/2018, 2:49:56 AM] /usr/lib/node_modules/homebridge-mi-air-purifier/index.js:296
    getLockPhysicalControls: async function(callback) {
                                   ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:72:22)
[6/28/2018, 2:49:56 AM] ====================

```

**Comment by Joeip12** [comment]
same problem here, please help.

![screenshot 2018-11-15 at 5 58 26 pm](https://user-images.githubusercontent.com/29377158/48547666-24b94f80-e906-11e8-9d16-858af61c7123.png)
