### ISSUE TITLE
The 1.4.0 version cannot register in homebridge

### ISSUE THREAD

**Issue by lxy1992** [seikan/homebridge-mi-air-purifier#57]
The plugin works fine in 1.2.2, but cannot work in 1.4.0
Hope the following error message may help you fix this issue. Thank you.
```
[7/30/2018, 10:05:40 PM] ---
[7/30/2018, 10:05:40 PM] ====================
[7/30/2018, 10:05:40 PM] ERROR LOADING PLUGIN homebridge-mi-air-purifier:
[7/30/2018, 10:05:40 PM] /usr/lib/node_modules/homebridge-mi-air-purifier/index.js:296
    getLockPhysicalControls: async function(callback) {
                                   ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Plugin.load (/usr/lib/node_modules/homebridge/lib/plugin.js:72:22)
[7/30/2018, 10:05:40 PM] ====================
```

**Comment by fenway062213** [comment]
Thanks for posting this. I know it’s been a while but I tried installing 1.2.2 when 1.4.0 wouldn’t work, but terminal is giving me an error message that that version isn’t found. Any ideas?
