### ISSUE TITLE
i have an error after installing the mii-air-purifier plugin

### ISSUE THREAD

**Issue by janj93** [seikan/homebridge-mi-air-purifier#9]
[7/11/2017, 6:17:38 AM] ---
[7/11/2017, 6:17:38 AM] ====================
[7/11/2017, 6:17:38 AM] ERROR LOADING PLUGIN homebridge-mi-air-purifier:
[7/11/2017, 6:17:38 AM] SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/miio/lib/devices/gateway.js:11:19)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/miio/lib/models.js:7:17)
    at Module._compile (module.js:434:26)
[7/11/2017, 6:17:38 AM] ====================

**Comment by janj93** [comment]
Can anybody help me pleas , I am still a noob in this homebridge thing I really can't fix it

**Comment by seikan** [comment]
Can you try to run the command below and share the output?

```miio --discover --sync```

**Comment by janj93** [comment]
This is What I get
[image1.JPG]

Verstuurd vanaf mijn iPhone

Op 13 jul. 2017 om 01:18 heeft Sei Kan <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Can you try to run the command below and share the output?

miio --discover --sync

**Comment by seikan** [comment]
Can you post the image to https://github.com/seikan/homebridge-mi-air-purifier/issues/9 ?

**Comment by janj93** [comment]
![image1](https://user-images.githubusercontent.com/30068055/28176265-092ab01a-67f7-11e7-82dd-b086557e9944.JPG)

**Comment by seikan** [comment]
Can you try to reinstall the `miio` package?

```
sudo npm -g uninstall miio
sudo npm -g install miio
```

**Comment by janj93** [comment]
![thumbnail_img_1831](https://user-images.githubusercontent.com/30068055/28211084-1c725fe8-689b-11e7-8798-2e6d3d6ca3c0.jpg)


it still doesn't work...

**Comment by janj93** [comment]
if i add the miairpurifer to the config.json the homebridge wil not run, and the i  get this error
![thumbnail_image1](https://user-images.githubusercontent.com/30068055/28228311-485e0b00-68de-11e7-87b3-df0bb5e9d9d9.jpg)

**Comment by janj93** [comment]
i finally fixed the error, the problem was that i was running the homebridge with node4.0.0  but 6.0.0 node is required, so i installed the version 6 en after that everything works good.
and thank you seikan for the help.
